name: redcupflipboard
description: An Alcohol game to play with your friends at party !

publish_to: 'none'
version: 1.0.7+8

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  appodeal_flutter: ^1.1.0
  audioplayers: ^0.16.2
  awesome_dialog: ^2.1.1
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.8.1
  flutter_layout_grid: ^1.0.3
  flutter_native_splash: ^0.3.2
  introduction_screen: ^2.1.0
  youtube_player_iframe: ^2.2.1

flutter_native_splash:
  color: "39465a"
  image: assets/flip512.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/